import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'AI运营',
      items: ['ai-analytics', 'ai-analytics-updates'],
    },
    {
      type: 'category',
      label: '浏览器插件',
      items: ['browser-plugin', 'browser-plugin-updates'],
    },
    {
      type: 'category',
      label: 'AI客服',
      items: ['customer-service', 'ai-customer-service-updates'],
    },
    {
      type: 'category',
      label: 'AI Agent',
      items: [
        {
          type: 'autogenerated',
          dirName: 'agntc',
        },
      ],
    },
    {
      type: 'category',
      label: 'CCLEE Theme',
      items: ['cclee-theme'],
    },
    {
      type: 'category',
      label: 'CCLEE Toolkit',
      items: ['cclee-toolkit', 'cclee-toolkit-image-alt', 'cclee-toolkit-seo', 'cclee-toolkit-woo'],
    },
    {
      type: 'category',
      label: 'WooCommerce 物流',
      items: ['cclee-shipping'],
    },
  ],
};

export default sidebars;
