export default {
  "00acca3d": [() => import(/* webpackChunkName: "00acca3d" */ "@site/docs/ai-analytics.md"), "@site/docs/ai-analytics.md", require.resolveWeak("@site/docs/ai-analytics.md")],
  "0abf49b1": [() => import(/* webpackChunkName: "0abf49b1" */ "@generated/docusaurus-plugin-content-docs/default/p/en-docs-b0f.json"), "@generated/docusaurus-plugin-content-docs/default/p/en-docs-b0f.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/en-docs-b0f.json")],
  "0e384e19": [() => import(/* webpackChunkName: "0e384e19" */ "@site/docs/intro.md"), "@site/docs/intro.md", require.resolveWeak("@site/docs/intro.md")],
  "1227b036": [() => import(/* webpackChunkName: "1227b036" */ "@site/docs/customer-service.md"), "@site/docs/customer-service.md", require.resolveWeak("@site/docs/customer-service.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1df93b7f": [() => import(/* webpackChunkName: "1df93b7f" */ "@site/src/pages/index.tsx"), "@site/src/pages/index.tsx", require.resolveWeak("@site/src/pages/index.tsx")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "a7456010": [() => import(/* webpackChunkName: "a7456010" */ "@generated/docusaurus-plugin-content-pages/default/__plugin.json"), "@generated/docusaurus-plugin-content-pages/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-pages/default/__plugin.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a8bb5334": [() => import(/* webpackChunkName: "a8bb5334" */ "@site/docs/guide.md"), "@site/docs/guide.md", require.resolveWeak("@site/docs/guide.md")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "bc957fd2": [() => import(/* webpackChunkName: "bc957fd2" */ "@site/docs/browser-plugin.md"), "@site/docs/browser-plugin.md", require.resolveWeak("@site/docs/browser-plugin.md")],};
